#!/usr/bin/env python3
"""Regenerate journal/INDEX.md, by-person/*, by-subsystem/* and PROMOTE_QUEUE.md.
Run automatically by GitHub Actions; you can also run it locally.

    python tools/build_indexes.py
"""
import os
import shutil

from common import (JOURNAL, ROOT, as_list, iter_entry_paths, load_team,
                    parse_entry, promote_value, scan_files)

GEN = "<!-- AUTO-GENERATED by tools/build_indexes.py - do not edit by hand -->\n\n"


def load_entries():
    out = []
    for p in iter_entry_paths():
        try:
            e = parse_entry(p)
        except ValueError as ex:
            print(f"skipping {p.relative_to(ROOT)}: {ex}")
            continue
        m = e["meta"]
        author = str(m.get("author", ""))
        people = [author] + [x for x in as_list(m.get("people")) if x != author]
        hours = m.get("hours")
        out.append({
            "path": p,
            "date": str(m.get("date", "")),
            "title": str(m.get("title") or p.stem),
            "author": author,
            "people": [x for x in people if x],
            "subsystems": as_list(m.get("subsystem")),
            "status": str(m.get("status", "")),
            "hours": hours if isinstance(hours, (int, float)) else 0,
            "promote": promote_value(m),
            "scans": len(scan_files(p)),
        })
    out.sort(key=lambda e: (e["date"], e["path"].name), reverse=True)
    return out


def rel(from_file, to):
    return os.path.relpath(to, from_file.parent).replace(os.sep, "/")


def table(entries, from_file):
    if not entries:
        return "_No entries yet._\n"
    rows = ["| Date | Title | Who | Subsystem | Hours | Status | Scans |", "|---|---|---|---|---|---|---|"]
    for e in entries:
        title = e["title"].replace("|", "\\|")
        link = f"[{title}]({rel(from_file, e['path'])})"
        scans = f"[{e['scans']}]({rel(from_file, e['path'].with_suffix(''))}/)" if e["scans"] else "-"
        rows.append(f"| {e['date']} | {link} | {', '.join(e['people'])} | {', '.join(e['subsystems'])} "
                    f"| {e['hours'] or ''} | {e['status']} | {scans} |")
    return "\n".join(rows) + "\n"


def total_hours(entries):
    return sum(e["hours"] for e in entries)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def main():
    team = load_team()
    entries = load_entries()
    by_person = {pid: [e for e in entries if pid in e["people"]] for pid in team["people"]}
    by_sub = {sid: [e for e in entries if sid in e["subsystems"]] for sid in team["subsystems"]}

    for d in ("by-person", "by-subsystem"):
        shutil.rmtree(JOURNAL / d, ignore_errors=True)

    # main index
    idx = JOURNAL / "INDEX.md"
    t = GEN + "# Litho journal - all entries\n\n"
    t += f"{len(entries)} entries, about {total_hours(entries):g} logged hours.\n\n"
    t += "**By person:** " + " | ".join(
        f"[{team['people'][p]['name']}](by-person/{p}.md) ({len(v)})" for p, v in by_person.items()) + "\n\n"
    t += "**By subsystem:** " + " | ".join(
        f"[{s}](by-subsystem/{s}.md) ({len(v)})" for s, v in by_sub.items()) + "\n\n"
    t += "**Waiting to be promoted into docs/:** [PROMOTE_QUEUE.md](PROMOTE_QUEUE.md)\n\n"
    t += table(entries, idx)
    write(idx, t)

    for pid, es in by_person.items():
        f = JOURNAL / "by-person" / f"{pid}.md"
        t = GEN + f"# Journal - {team['people'][pid]['name']}\n\n"
        t += f"{len(es)} entries, about {total_hours(es):g} logged hours. [Back to index](../INDEX.md)\n\n"
        t += table(es, f)
        write(f, t)

    for sid, es in by_sub.items():
        f = JOURNAL / "by-subsystem" / f"{sid}.md"
        t = GEN + f"# Journal - {sid}\n\n"
        t += f"{len(es)} entries. Verified knowledge for this subsystem lives in `{team['subsystems'][sid]}/`. "
        t += "[Back to index](../INDEX.md)\n\n"
        t += table(es, f)
        write(f, t)

    # promotion queue
    q = JOURNAL / "PROMOTE_QUEUE.md"
    todo = [e for e in entries if e["promote"] == "yes"]
    t = GEN + "# Waiting to be promoted into docs/\n\n"
    t += ("Entries marked `promote_to_docs: \"yes\"`. When the result is verified, distil it into the docs folder "
          "via a pull request, then change the entry to `\"done\"` and add `promoted_in: docs/...`.\n\n")
    if todo:
        t += "| Date | Entry | Who | Put it in |\n|---|---|---|---|\n"
        for e in todo:
            dest = ", ".join(sorted({team["subsystems"][s] for s in e["subsystems"] if s in team["subsystems"]}))
            t += f"| {e['date']} | [{e['title'].replace('|', chr(92) + '|')}]({rel(q, e['path'])}) | {', '.join(e['people'])} | {dest} |\n"
    else:
        t += "_Nothing waiting._\n"
    write(q, t)

    print(f"indexed {len(entries)} entries -> INDEX.md, {len(by_person)} person pages, "
          f"{len(by_sub)} subsystem pages, PROMOTE_QUEUE.md")


if __name__ == "__main__":
    main()
